package com.ttsham6.shared.domain.book;

import java.util.List;
import java.util.UUID;
import org.springframework.lang.NonNull;
import org.springframework.lang.Nullable;

public record Book(
    @NonNull String id,
    @NonNull String title,
    @NonNull String author,
    @Nullable String artistName,
    @NonNull String publisherName,
    @Nullable String label,
    @NonNull String isbn,
    @Nullable String jan,
    @Nullable String hardware,
    @Nullable String os,
    @NonNull String itemCaption,
    @NonNull String salesDate,
    long itemPrice,
    long listPrice,
    double discountRate,
    double discountPrice,
    @NonNull String itemUrl,
    @Nullable String affiliateUrl,
    @Nullable String smallImageUrl,
    @Nullable String mediumImageUrl,
    @Nullable String largeImageUrl,
    @Nullable String chirayomiUrl,
    @NonNull Availability availability,
    @NonNull PostageFlag postageFlag,
    boolean isLimited,
    long reviewCount,
    double reviewAverage,
    @Nullable List<Integer> genreIds) {

  public Book(
      @NonNull String title,
      @NonNull String author,
      @Nullable String artistName,
      @NonNull String publisherName,
      @Nullable String label,
      @NonNull String isbn,
      @Nullable String jan,
      @Nullable String hardware,
      @Nullable String os,
      @NonNull String itemCaption,
      @NonNull String salesDate,
      long itemPrice,
      long listPrice,
      double discountRate,
      double discountPrice,
      @NonNull String itemUrl,
      @Nullable String affiliateUrl,
      @Nullable String smallImageUrl,
      @Nullable String mediumImageUrl,
      @Nullable String largeImageUrl,
      @Nullable String chirayomiUrl,
      @NonNull Availability availability,
      @NonNull PostageFlag postageFlag,
      boolean isLimited,
      long reviewCount,
      double reviewAverage,
      @Nullable List<Integer> genreIds) {
    this(
        UUID.randomUUID().toString(),
        title,
        author,
        artistName,
        publisherName,
        label,
        isbn,
        jan,
        hardware,
        os,
        itemCaption,
        salesDate,
        itemPrice,
        listPrice,
        discountRate,
        discountPrice,
        itemUrl,
        affiliateUrl,
        smallImageUrl,
        mediumImageUrl,
        largeImageUrl,
        chirayomiUrl,
        availability,
        postageFlag,
        isLimited,
        reviewCount,
        reviewAverage,
        genreIds);
  }
}
